stages:
  # - env
  - dependencies
  - lint
  - test
  - build
  # - e2e
  - package
  - deploy
  - clean_up

variables:
  APK_CACHE_DIR: $CI_PROJECT_DIR/cache/apk
  NPMRC_PATH: $CI_PROJECT_DIR/./.npmrc
  SENTRY_CLI_RC_PATH: $CI_PROJECT_DIR/.sentryclirc
  npm_config_cache: $CI_PROJECT_DIR/.npm
  # CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/Cypress
  ENV_STAGE: ""

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - $APK_CACHE_DIR
    - $npm_config_cache
    - node_modules
    # - cache/Cypress

# SKIP SYNTAX ERROR
.rules_env_stage: &rules_env_stage
  - if: $CI_COMMIT_REF_NAME == "staging"
    when: on_success
    variables:
      ENV_STAGE: $ENV_STAGING
  - if: $CI_COMMIT_REF_NAME == "main"
    when: on_success
    variables:
      ENV_STAGE: $ENV_PRODUCTION

# ------ env ------
.env_script: &env_script
  - cp $NPMRC_FILE $NPMRC_PATH | true
  - cp $SENTRYRC_FILE $SENTRY_CLI_RC_PATH | true
  - source $ENV_DEFAULT | true
  - source $ENV_STAGE | true
  - ls -lsa
  - cat ./package.json

# ------ dependencies stage ------
.dependencies_common:
  image: node:16.13.1-alpine
  rules: *rules_env_stage
  before_script:
    - *env_script
    - node -v
    - npm -v
    - yarn config set cache-folder $npm_config_cache
    - yarn install --frozen-lockfile --emoji=false --silent --production=false

dependencies:
  extends: .dependencies_common
  stage: dependencies
  script:
    - echo "dependencies"
  rules:
    - when: on_success

# ------ lint stage ------
lint:
  extends: .dependencies_common
  stage: lint
  needs: [dependencies]
  script:
    - yarn lint
  rules:
    - if: $CI_COMMIT_REF_NAME != "staging" && $CI_COMMIT_REF_NAME != "main"
      when: on_success

test:
  extends: .dependencies_common
  stage: test
  needs: [dependencies]
  script:
    - yarn jest:ci
  rules:
    - when: on_success

# ------ build stage ------
build:
  extends: .dependencies_common
  stage: build
  needs:
    - job: dependencies
    # - job: lint
    - job: test
  script:
    - SENTRY_DISABLE=true yarn build
  artifacts:
    paths:
      - .next
      - build
    expire_in: 1 day

# ------ e2e stage ------
# e2e:
#   extends: .dependencies_common
#   stage: e2e
#   image: cypress/browsers:node16.13.0-chrome95-ff94
#   needs:
#     - job: build
#       artifacts: true
#     - job: dependencies
#   # parallel: 3
#   script:
#     - npx cypress cache path
#     - npx cypress cache list
#     - yarn cy:verify
#     - yarn cy:info
#     - yarn e2e:run -- --parallel --group "electrons on GitLab CI"
#   artifacts:
#     when: always
#     paths:
#       - cypress/videos/**/*.mp4
#       - cypress/screenshots/**/*.png
#     expire_in: 1 day

# ------ package stage ------
package:
  stage: package
  image: docker
  needs:
    - job: build
      artifacts: true
    # - job: e2e
  rules: *rules_env_stage
  before_script:
    - *env_script
    - mkdir -p $APK_CACHE_DIR
    - apk add --cache-dir $APK_CACHE_DIR docker-compose
    - docker info
    - docker-compose version
    - docker-compose config
  script:
    - echo ${HUB_PASSWORD} | docker login -u ${HUB_USER} http://nexus.mvbureev.tech:10010 --password-stdin
    - echo ${HUB_PASSWORD} | docker login -u ${HUB_USER} http://nexus.mvbureev.tech:10011 --password-stdin
    - docker-compose pull
    # - docker logout http://nexus.mvbureev.tech:10010
    - docker-compose build
    - docker-compose push
    - export CUSTOM_VERSION_FOR_IMAGE=$CI_COMMIT_REF_NAME
    - docker-compose build
    - docker-compose push
    - export CUSTOM_VERSION_FOR_IMAGE=$CI_COMMIT_SHORT_SHA
    - docker-compose build
    - docker-compose push

# ------ deploy stage ------
deploy:
  stage: deploy
  image: docker
  needs: ["package"]
  rules:
    - *rules_env_stage
    - if: $CI_COMMIT_REF_NAME == "main"
      when: manual
  before_script:
    - *env_script
    - mkdir -p $APK_CACHE_DIR
    - apk add --cache-dir $APK_CACHE_DIR docker-compose
    - docker-compose ps
  script:
    - export CUSTOM_VERSION_FOR_IMAGE=$CI_COMMIT_SHORT_SHA
    - docker-compose up -d

clean_up:
  image: node:16.13.1-alpine
  stage: clean_up
  script:
    - rm -rf node_modules
  when: on_failure
