image: docker/compose

cache:
  key: cache-${CI_PROJECT_TITLE}-${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - mvbureev
  before_script:
    - ls -lsa
    - docker info
    - docker-compose version
    - docker-compose config
  script:
    - docker-compose pull
    - docker-compose build
  only:
  - main

deploy:
  stage: deploy
  tags:
    - mvbureev
  before_script:
    - docker-compose ps
  script:
    - docker-compose up -d
  only:
  - main
