version: "3.8"

services:
  proxy:
    image: "proxy"
    build:
      dockerfile: Dockerfile
      context: ./nginx
      cache_from:
      - "proxy"
    restart: always
    environment:
      CERTBOT_EMAIL: "mvbureev@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mvbureev-landing

  nextjs:
    image: "nextjs"
    build:
      dockerfile: Dockerfile
      context: ./
      cache_from:
      - "nextjs"
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - "3001:3001"
    networks:
      - mvbureev-landing

networks:
  mvbureev-landing:
    driver: bridge
