version: "3.7"

services:
  test-nextjs:
    image: test-nextjs
    container_name: test-nextjs
    networks:
      - proxy
    build:
      dockerfile: Dockerfile
      context: ./
      cache_from:
      - test-nextjs
    restart: unless-stopped

  test-proxy:
    image: test-proxy
    container_name: test-proxy
    networks:
      - proxy
    depends_on:
      - test-nextjs
    build:
      dockerfile: Dockerfile
      context: ./nginx
      cache_from:
      - test-proxy
    restart: always
    labels:
      - traefik.http.routers.test.rule=Host("test.${DOMAIN}")
      - traefik.http.routers.test.entrypoints=https
      - traefik.http.routers.test.tls=true
      - traefik.http.routers.test.tls.certresolver=${CERT_RESOLVER}
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
